# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(868, 530)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.fileDir = QtWidgets.QLineEdit(Form)
        self.fileDir.setObjectName("fileDir")
        self.horizontalLayout.addWidget(self.fileDir)
        self.fileDirBut = QtWidgets.QPushButton(Form)
        self.fileDirBut.setObjectName("fileDirBut")
        self.horizontalLayout.addWidget(self.fileDirBut)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_5.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.fileFilter = QtWidgets.QLineEdit(Form)
        self.fileFilter.setObjectName("fileFilter")
        self.verticalLayout_2.addWidget(self.fileFilter)
        self.verticalLayout_5.addLayout(self.verticalLayout_2)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.encodeing = QtWidgets.QComboBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.encodeing.sizePolicy().hasHeightForWidth())
        self.encodeing.setSizePolicy(sizePolicy)
        self.encodeing.setObjectName("encodeing")
        self.encodeing.addItem("")
        self.encodeing.addItem("")
        self.encodeing.addItem("")
        self.encodeing.addItem("")
        self.encodeing.addItem("")
        self.encodeing.addItem("")
        self.verticalLayout_4.addWidget(self.encodeing)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.output = QtWidgets.QTextEdit(Form)
        self.output.setReadOnly(True)
        self.output.setObjectName("output")
        self.verticalLayout_3.addWidget(self.output)
        self.verticalLayout_5.addLayout(self.verticalLayout_3)
        self.cover = QtWidgets.QPushButton(Form)
        self.cover.setObjectName("cover")
        self.verticalLayout_5.addWidget(self.cover)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "文件夹选择"))
        self.fileDir.setPlaceholderText(_translate("Form", "选择文件夹路径"))
        self.fileDirBut.setText(_translate("Form", "路径"))
        self.label.setText(_translate("Form", "文件过滤器. 空格间隔. 输入示例: *.c *.h *.cpp"))
        self.fileFilter.setText(_translate("Form", "*.c *.h *.cpp *.hpp"))
        self.fileFilter.setPlaceholderText(_translate("Form", "选择文件类型,空格作为间隔,示例: *.c *.h "))
        self.label_4.setText(_translate("Form", "目标格式"))
        self.encodeing.setItemText(0, _translate("Form", "utf-8"))
        self.encodeing.setItemText(1, _translate("Form", "gb2312"))
        self.encodeing.setItemText(2, _translate("Form", "ascii"))
        self.encodeing.setItemText(3, _translate("Form", "gb18030"))
        self.encodeing.setItemText(4, _translate("Form", "gbk"))
        self.encodeing.setItemText(5, _translate("Form", "utf_16"))
        self.label_3.setText(_translate("Form", "日志输出"))
        self.cover.setText(_translate("Form", "转换"))
